<?php
session_start(); require_once '../config/db.php';
require_once '../includes/seguridad.php';
seguridad_exigir_superadmin($pdo, false);
if(empty($_SESSION['id_usuario'])||empty($_SESSION['es_superadmin'])){http_response_code(403);exit('Acceso denegado');}
$a=$_POST['accion']??'';
if($a==='ver'){
 $u=(int)($_POST['id_user']??0);$z=(int)($_POST['id_zona']??0);$s=$pdo->prepare('SELECT id_empresa,razon_social,rfc FROM empresas WHERE id_zona=? AND activo=1 ORDER BY razon_social');$s->execute([$z]);$emps=$s->fetchAll(PDO::FETCH_ASSOC);
 $s=$pdo->prepare('SELECT ue.id_empresa,p.* FROM usuario_empresas ue LEFT JOIN usuario_empresa_documentos p ON p.id_usuario=ue.id_usuario AND p.id_empresa=ue.id_empresa WHERE ue.id_usuario=?');$s->execute([$u]);$as=[];foreach($s->fetchAll(PDO::FETCH_ASSOC) as $r)$as[(int)$r['id_empresa']]=$r;
 echo '<div class="list-group list-group-flush">';foreach($emps as $e){$id=(int)$e['id_empresa'];$sel=isset($as[$id]);$p=$as[$id]??[];$dis=$sel?'':'disabled';$on=function($c)use($p){return !array_key_exists($c,$p)||(int)$p[$c]===1;};
  $btn=function($label,$attr,$value,$active,$cls='')use($dis){return "<button type='button' class='perm-btn {$cls}".($active?' activo':'')."' {$attr}='{$value}' data-selected='".($active?'1':'0')."' onclick='alternarPermiso(this)' {$dis}>{$label}</button>";};
  $docCols=['I'=>['Ingreso','ver_ingreso'],'E'=>['Egreso','ver_egreso'],'P'=>['Pago','ver_pago'],'N'=>['Nómina','ver_nomina'],'T'=>['Traslado','ver_traslado']];$accCols=['ver_xml_pdf'=>['Ver XML / PDF','ver_xml_pdf'],'descargar_xml'=>['Descargar XML','descargar_xml'],'descargar_pdf'=>['Descargar PDF','descargar_pdf'],'exportar'=>['Exportar Excel / CSV / archivos','exportar'],'procesar_pagos'=>['Procesar pagos','procesar_pagos'],'generar_diot'=>['Generar DIOT','generar_diot'],'ver_solicitudes_sat'=>['Solicitudes SAT','ver_solicitudes_sat'],'contpaq_cheques'=>['CONTPAQ Cheques','contpaq_cheques'],'oracle_pagos'=>['Oracle Pagos','oracle_pagos'],'nomina_archivo'=>['Nómina archivo semanal','nomina_archivo']];$satCols=['consulta_cruce_metadata'=>['Cruce Metadata / CFDI','consulta_cruce_metadata'],'consulta_codigos_postales'=>['Códigos postales','consulta_codigos_postales'],'consulta_sat_69'=>['Artículo 69','consulta_sat_69'],'consulta_alertas_69'=>['Riesgos 69','consulta_alertas_69'],'consulta_sat_69b'=>['Artículo 69-B','consulta_sat_69b'],'consulta_alertas_69b'=>['Alertas 69-B','consulta_alertas_69b']];
  $allD=true;foreach($docCols as $x)$allD=$allD&&$on($x[1]);$allA=true;foreach($accCols as $x)$allA=$allA&&$on($x[1]);$allS=true;foreach($satCols as $x)$allS=$allS&&$on($x[1]);$checked=$sel?'checked':'';
  echo "<div class='list-group-item empresa-permisos' data-id-empresa='{$id}'><div class='d-flex gap-3 align-items-start'><input class='form-check-input mt-1 chk-empresa' type='checkbox' value='{$id}' {$checked} onchange='togglePermisosEmpresa({$id},this.checked)'><div class='flex-grow-1'><div class='fw-bold'>".htmlspecialchars($e['razon_social'])."</div><div class='text-muted small'>RFC: ".htmlspecialchars($e['rfc'])."</div>";
  echo "<div class='perm-grupo'><div class='perm-titulo'><i class='bi bi-file-earmark-lock2 me-1'></i>Documentos que puede consultar</div><div class='perm-selector'><button type='button' class='perm-btn perm-todos-docs".($allD?' activo':'')."' onclick=\"seleccionarTodos(this,'docs')\" {$dis}>Todos</button>";foreach($docCols as $k=>$x)echo $btn($x[0],'data-tipo',$k,$on($x[1])).($dis?'<script></script>':'');echo "</div></div>";
  echo "<div class='perm-grupo'><div class='perm-titulo'><i class='bi bi-bar-chart-line me-1'></i>Funciones, reportes y descargas</div><div class='perm-selector'><button type='button' class='perm-btn perm-todos-acciones".($allA?' activo':'')."' onclick=\"seleccionarTodos(this,'acc')\" {$dis}>Todos</button>";foreach($accCols as $k=>$x)echo $btn($x[0],'data-accion',$k,$on($x[1]));echo "</div></div>";
  echo "<div class='perm-grupo'><div class='perm-titulo'><i class='bi bi-shield-check me-1'></i>Consultas y validaciones SAT</div><div class='perm-selector'><button type='button' class='perm-btn perm-todos-sat".($allS?' activo':'')."' onclick=\"seleccionarTodos(this,'sat')\" {$dis}>Todos</button>";foreach($satCols as $k=>$x)echo $btn($x[0],'data-sat',$k,$on($x[1]));echo "</div></div></div></div></div>";
 }
 echo '</div>';exit;
}
if($a==='guardar'){header('Content-Type: application/json');$u=(int)($_POST['id_user']??0);$arr=json_decode($_POST['asignaciones']??'[]',true);if(!is_array($arr))$arr=[];try{$pdo->beginTransaction();$pdo->prepare('DELETE FROM usuario_empresa_documentos WHERE id_usuario=?')->execute([$u]);$pdo->prepare('DELETE FROM usuario_empresas WHERE id_usuario=?')->execute([$u]);$ie=$pdo->prepare('INSERT INTO usuario_empresas VALUES (?,?)');$ip=$pdo->prepare('INSERT INTO usuario_empresa_documentos (id_usuario,id_empresa,ver_ingreso,ver_egreso,ver_pago,ver_nomina,ver_traslado,ver_xml_pdf,descargar_xml,descargar_pdf,exportar,procesar_pagos,generar_diot,ver_solicitudes_sat,contpaq_cheques,oracle_pagos,nomina_archivo,consulta_cruce_metadata,consulta_codigos_postales,consulta_sat_69,consulta_alertas_69,consulta_sat_69b,consulta_alertas_69b) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');foreach($arr as $r){$e=(int)($r['id_empresa']??0);if(!$e)continue;$t=array_map('strtoupper',$r['tipos']??[]);$ac=$r['acciones']??[];$sat=$r['sat']??[];$ie->execute([$u,$e]);$vals=[$u,$e];foreach(['I','E','P','N','T'] as $x)$vals[]=in_array($x,$t,true)?1:0;foreach(['ver_xml_pdf','descargar_xml','descargar_pdf','exportar','procesar_pagos','generar_diot','ver_solicitudes_sat','contpaq_cheques','oracle_pagos','nomina_archivo'] as $x)$vals[]=in_array($x,$ac,true)?1:0;foreach(['consulta_cruce_metadata','consulta_codigos_postales','consulta_sat_69','consulta_alertas_69','consulta_sat_69b','consulta_alertas_69b'] as $x)$vals[]=in_array($x,$sat,true)?1:0;$ip->execute($vals);} $pdo->commit();echo json_encode(['success'=>true]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();seguridad_log_error($e, 'asignacion_operaciones'); echo json_encode(['success'=>false,'error'=>'No se pudo guardar la asignación.']);}exit;}
