<?php
if (PHP_SAPI!=='cli') {http_response_code(404);exit;}
require_once __DIR__.'/../includes/nomina_conceptos.php';
$checks=0;
function ck($value,string $message): void {global $checks;$checks++;if(!$value)throw new RuntimeException($message);}
$uuid='00000000-0000-4000-8000-000000000001';$rfc='TEST010101AB1';
$xml='<c:Comprobante xmlns:c="http://www.sat.gob.mx/cfd/4" xmlns:n="http://www.sat.gob.mx/nomina12" xmlns:t="http://www.sat.gob.mx/TimbreFiscalDigital" TipoDeComprobante="N" Total="140.00"><c:Emisor Rfc="MGU840223U79"/><c:Receptor Rfc="TEST010101AB1"/><c:Complemento><n:Nomina Version="1.2" TipoNomina="O" FechaPago="2026-07-04" FechaInicialPago="2026-06-25" FechaFinalPago="2026-07-01" TotalPercepciones="100.00" TotalDeducciones="10.00" TotalOtrosPagos="50.00"><n:Receptor NumEmpleado="0010" Curp="CURPTEST" NumSeguridadSocial="000123"/><n:Percepciones><n:Percepcion Clave="P002" TipoPercepcion="001" Concepto="Sueldos" ImporteGravado="90" ImporteExento="10"/></n:Percepciones><n:Deducciones><n:Deduccion Clave="D016" TipoDeduccion="002" Concepto="ISR" Importe="10"/></n:Deducciones><n:OtrosPagos><n:OtroPago Clave="P065" TipoOtroPago="999" Concepto="Prestamo" Importe="50"/><n:OtroPago Clave="D019" TipoOtroPago="002" Concepto="Subsidio" Importe="0"><n:SubsidioAlEmpleo SubsidioCausado="20"/></n:OtroPago></n:OtrosPagos></n:Nomina><t:TimbreFiscalDigital UUID="00000000-0000-4000-8000-000000000001"/></c:Complemento></c:Comprobante>';
$base=['uuid'=>$uuid,'rfc_receptor'=>$rfc,'rfc_emisor'=>'MGU840223U79','estatus_sat'=>'VIGENTE','xml_base64'=>$xml];
$scope=['desde'=>'2026-06-25','hasta'=>'2026-07-01','rfc_emisor'=>'MGU840223U79'];
$d=ncc_document($base,$scope);ck($d['estado']==='INCLUIDO','Fixture incluido');ck(count($d['conceptos'])===4,'Se leen padres sin atributos, incluidos OtrosPagos');ck($d['totales']['TOTALPER']===150000000,'Otros pagos se suman al total de referencia');ck($d['conceptos'][3]['importe']===0 && $d['conceptos'][3]['subsidio_causado']===20000000,'No confundir causado con entregado');
foreach([$xml,"\xEF\xBB\xBF\xEF\xBB\xBF".$xml,base64_encode("\xEF\xBB\xBF\xEF\xBB\xBF".$xml)] as $raw)ck(ncc_document(array_merge($base,['xml_base64'=>$raw]),$scope)['estado']==='INCLUIDO','BOM/base64');
foreach([substr($xml,0,-3),'<!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]>'.$xml,str_replace($uuid,'otro',$xml)] as $raw)ck(ncc_document(array_merge($base,['xml_base64'=>$raw]),$scope)['estado']==='INCIDENCIA','Rechaza truncado/DTD/UUID ajeno');
ck(ncc_document(array_merge($base,['estatus_sat'=>'CANCELADO']),$scope)['estado']==='CANCELADO','Cancelados no suman');ck(ncc_document(array_merge($base,['estatus_sat'=>'']),$scope)['estado']==='INCIDENCIA','Estatus desconocido no vigente');
ck(ncc_document($base,array_merge($scope,['rfc_emisor'=>'OTRA010101AA1']))['estado']==='INCIDENCIA','Empresa ajena');ck(ncc_document($base,array_merge($scope,['hasta'=>'2026-06-30']))['estado']==='INCIDENCIA','No prorratear período cortado');ck(ncc_document($base,array_merge($scope,['desde'=>'2026-07-02','hasta'=>'2026-07-29']))['estado']==='FUERA_RANGO','Filtrar por período, no pago');
ck(ncc_document(array_merge($base,['xml_base64'=>str_replace('Total="140.00"','Total="140.50"',$xml)]),$scope)['estado']==='INCIDENCIA','Validación total');
$cols=[];foreach(['P002 - Sueldos','D016 - ISR','P065 - Préstamo','D019 - Subsidio','I001 - Provisión','Id Empleado','P999 - Nuevo'] as $i=>$h)$cols[]=['indice'=>$i,'letra'=>rxr_col_name($i+1),'encabezado'=>$h,'clave_campo'=>nf_field_key($h),'estado_al_importar'=>$i===6?'PENDIENTE':'ACTIVO'];
$rows=[['renglon'=>5,'clase'=>'EMPLEADO','numero_empleado'=>'0010','rfc'=>$rfc,'valores'=>[80,10,50,0,70,'0010',null]],['renglon'=>6,'clase'=>'ADICIONAL','numero_empleado'=>'0010','rfc'=>$rfc,'valores'=>[20,null,null,null,null,null,123]]];
$w=ncc_workbook($cols,$rows,$scope['rfc_emisor']);$a=ncc_aggregate([$d,$d]);$we=$w['empleados'][$rfc];$xe=$a['empleados'][$rfc];ck($xe['validos']===1,'UUID duplicado no duplica importes');ck($we['valores'][0]['sum']===100000000 && $we['renglones']===[5,6],'Continuaciones vinculadas');
foreach([0,1,2,5] as $i)ck(ncc_compare($w['columnas'][$i],$we,$xe,$scope)['estado']==='COINCIDE','Comparación clave / atributo '.$i);
ck(ncc_compare($w['columnas'][3],$we,$xe,$scope)['estado']==='SIN_MOVIMIENTO','Cero y subsidio causado distintos');ck(ncc_compare($w['columnas'][4],$we,$xe,$scope)['estado']==='PENDIENTE_REGLA','No inventar provisiones');ck(ncc_compare($w['columnas'][6],$we,$xe,$scope)['estado']==='PENDIENTE_REGLA','Campo nuevo preservado sin bloquear resto');
$ww=$we;$ww['valores'][0]['sum']=99000000;ck(ncc_compare($w['columnas'][0],$ww,$xe,$scope)['estado']==='DIFERENCIA','Diferencia por campo');
$xx=$xe;$xx['incidencias']=1;ck(ncc_compare($w['columnas'][0],$we,$xx,$scope)['estado']==='XML_INCOMPLETO','Incidencia no da falso positivo');ck(ncc_compare($w['columnas'][0],$we,$xe,array_merge($scope,['hasta'=>'2026-07-29']))['estado']==='COBERTURA_PARCIAL','Una semana no valida acumulado');
ck(ncc_compare($w['columnas'][0],$we,null,$scope)['xml']===null,'Sin XML no cero');ck(ncc_compare($w['columnas'][0],null,$xe,$scope)['estado']==='SOLO_XML','Solo XML');
ck(ncc_compare($w['columnas'][5],null,$xe,$scope)['estado']==='SOLO_XML','Identificador sólo XML');
$bad=$d;$bad['conceptos'][0]['tipo']='999';$badA=ncc_aggregate([$bad]);ck(ncc_compare($w['columnas'][0],$we,$badA['empleados'][$rfc],$scope)['estado']==='REVISAR_EQUIVALENCIA','Clave mismo nombre pero otro tipo SAT');
$cc=$cols[0];$cc['estado_al_importar']='AMBIGUO';ck(ncc_plan($cc,$scope['rfc_emisor'])['modo']==='pendiente','Código repetido no mezclado');ck(ncc_plan($cols[0],'OTRA010101AA1')['modo']==='pendiente','Reglas GKM no asignadas a otra empresa');
$reverse=array_reverse($cols);$wr=ncc_workbook($reverse,$rows,$scope['rfc_emisor']);ck(ncc_compare($wr['columnas'][6],$wr['empleados'][$rfc],$xe,$scope)['estado']==='COINCIDE','Recorrido reordenado independiente de posición');
$rotated=array_merge(array_slice($cols,2),array_slice($cols,0,2));$movedRows=$rows;
foreach($rotated as $i=>&$column){$old=$column['indice'];$column['indice']=$i;$column['letra']=rxr_col_name($i+1);foreach($rows as $j=>$row)$movedRows[$j]['valores'][$i]=$row['valores'][$old];}unset($column);
$rw=ncc_workbook($rotated,$movedRows,$scope['rfc_emisor']);$sueldos=array_values(array_filter($rw['columnas'],fn($c)=>$c['clave_campo']==='CODIGO:P002'))[0];ck(ncc_compare($sueldos,$rw['empleados'][$rfc],$xe,$scope)['estado']==='COINCIDE','Columnas físicamente movidas y valores reordenados');
$year=['indice'=>7,'letra'=>'H','encabezado'=>'AÑO','clave_campo'=>nf_field_key('AÑO'),'estado_al_importar'=>'ACTIVO'];ck(ncc_plan($year,$scope['rfc_emisor'])['atributo']==='Ejercicio' && $d['atributos']['Ejercicio']==='2026','Ejercicio desde FechaPago');
$extra='<n:Nomina Version="1.2" TipoNomina="E" FechaPago="2026-07-04" FechaInicialPago="2026-06-25" FechaFinalPago="2026-07-01" TotalPercepciones="5"><n:Receptor NumEmpleado="0010"/><n:Percepciones><n:Percepcion Clave="T041" TipoPercepcion="025" Concepto="Indemnizacion" ImporteGravado="0" ImporteExento="5"/></n:Percepciones></n:Nomina>';
$multi=str_replace(['Total="140.00"','<t:TimbreFiscalDigital'],['Total="145.00"',$extra.'<t:TimbreFiscalDigital'],$xml);$md=ncc_document(array_merge($base,['xml_base64'=>$multi]),$scope);ck($md['estado']==='INCLUIDO' && $md['complementos']===2 && $md['totales']['TOTALPER']===155000000,'Varios complementos, neto una sola vez');
$multi=str_replace('TotalPercepciones="5"','TotalPercepciones="6"',$multi);ck(ncc_document(array_merge($base,['xml_base64'=>$multi]),$scope)['estado']==='INCIDENCIA','Validar cada complemento');
ck(ncc_covered([['2026-06-25','2026-07-01'],['2026-07-02','2026-07-08']],'2026-06-25','2026-07-08'),'Cobertura contigua');ck(!ncc_covered([['2026-06-25','2026-07-01'],['2026-07-03','2026-07-08']],'2026-06-25','2026-07-08'),'Detectar hueco');
echo "OK: $checks comprobaciones de conceptos, seguridad XML, tipos, totales, fechas y datos pendientes.\n";
