<?php
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
// Reutiliza los XML sintéticos y comprobaciones del motor anterior, sin datos personales.
require __DIR__.'/nomina_conceptos_test.php';
$checks=0;
function rejected(callable $fn,string $msg):void {try{$fn();}catch(Throwable $e){ck(true,$msg);return;}ck(false,$msg);}
$x=ncm_parse_sample("\xEF\xBB\xBF\xEF\xBB\xBF".$xml,$scope['rfc_emisor']);$dis=ncm_discover($x);
ck(count($dis)>30,'Descubrimiento de atributos y conceptos');
$by=[];foreach($dis as $f){$by[$f['etiqueta']]=$f;ck(ncm_select($x,$f['selector'])['valores']!==[],'Cada selector descubierto recupera valores');}
$prefix=str_replace(['xmlns:c=','xmlns:n=','<c:','</c:','<n:','</n:'],['xmlns:cfdi=','xmlns:nomina12=','<cfdi:','</cfdi:','<nomina12:','</nomina12:'],$xml);
$alt=ncm_discover(ncm_parse_sample($prefix,$scope['rfc_emisor']));ck(array_column($dis,'hash')===array_column($alt,'hash'),'Prefijos distintos conservan identidad');
function selector_for(array $items,string $suffix):array{foreach($items as $f)if(str_ends_with($f['etiqueta'],$suffix))return $f;throw new RuntimeException('No existe selector '.$suffix);}
$g=selector_for($dis,'Percepcion[Clave=P002, TipoPercepcion=001]@ImporteGravado');$ex=selector_for($dis,'Percepcion[Clave=P002, TipoPercepcion=001]@ImporteExento');
$def=['estado'=>'RELACIONADO','tipo_workbeat'=>'NUMERO','operacion'=>'SUMA','ausencia'=>'PENDIENTE','descripcion'=>'Sueldos gravado + exento','revision'=>1,'terminos'=>[['selector'=>$g['selector'],'signo'=>1],['selector'=>$ex['selector'],'signo'=>1]]];
ck(ncm_eval($x,$def)['sum']===100000000,'Suma gravado más exento');ck(ncm_eval(ncm_parse_sample($prefix,$scope['rfc_emisor']),$def)['sum']===100000000,'Evaluación independiente del prefijo');
$minus=$def;$minus['terminos'][1]['signo']=-1;ck(ncm_eval($x,$minus)['sum']===80000000,'Restar componente');
$absent=rng_parse(str_replace('Clave="P002"','Clave="P999"',$xml));ck(ncm_eval($absent,$def)['faltan']===2,'Ausencias pendientes por defecto');$zero=$def;$zero['ausencia']='CERO';ck(ncm_eval($absent,$zero)['faltan']===0 && ncm_eval($absent,$zero)['sum']===0,'Cero sólo por ausencia autorizada');
$attrMissing=rng_parse(str_replace(' ImporteExento="10"','',$xml));ck(ncm_eval($attrMissing,$zero)['faltan']===1,'Atributo omitido no es cero');
$changed=rng_parse(str_replace('TipoPercepcion="001"','TipoPercepcion="999"',$xml));ck(count(ncm_eval($changed,$zero)['errores'])===1,'Cambio de tipo SAT rechazado');
$group=rng_parse(str_replace(['<n:Percepcion Clave="P002" TipoPercepcion="001"','<n:Percepciones>','</n:Percepciones>'],['<n:OtroPago Clave="P002" TipoOtroPago="999"','<n:OtrosPagos>','</n:OtrosPagos>'],$xml));ck(count(ncm_eval($group,$zero)['errores'])===1,'Clave en otro grupo no se toma como cero');
$ns=rng_parse(str_replace('http://www.sat.gob.mx/nomina12','http://www.sat.gob.mx/nominaNueva',$xml));ck(count(ncm_eval($ns,$zero)['errores'])===1,'Namespace cambiado requiere revisión');
$multiple=rng_parse(str_replace('<t:TimbreFiscalDigital',str_replace(['Clave="T041"','TipoPercepcion="025"'],['Clave="P002"','TipoPercepcion="001"'],$extra).'<t:TimbreFiscalDigital',$xml));ck(ncm_eval($multiple,$def)['sum']===105000000,'Suma varios complementos sin perder el segundo');
$pay=selector_for($dis,'Nomina@FechaPago');$yearRule=['estado'=>'RELACIONADO','tipo_workbeat'=>'TEXTO','operacion'=>'ANIO','ausencia'=>'PENDIENTE','descripcion'=>'Ejercicio','terminos'=>[['selector'=>$pay['selector'],'signo'=>1]]];ck(array_keys(ncm_eval($x,$yearRule)['textos'])===[2026],'Año desde fecha de pago');ck(ncm_text(2026,'ANIO',true)==='2026','Año del Excel no es serial');ck(ncm_text(46207,'FECHA',true)==='2026-07-04','Serial Excel como fecha');
ck(ncm_text('100.001000','NUMERO_UNICO')===ncm_text(100.001,'NUMERO_UNICO',true),'Número único normaliza decimales sin sumarlos');ck(ncm_text('-0.0100','NUMERO_UNICO')==='-0.01','Número único conserva signo y precisión');
rejected(fn()=>ncm_parse_sample('<!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]>'.$xml,$scope['rfc_emisor']),'DTD rechazado');rejected(fn()=>ncm_parse_sample(substr($xml,0,-3),$scope['rfc_emisor']),'XML truncado rechazado');rejected(fn()=>ncm_parse_sample($xml,'OTRA010101AB1'),'Emisor ajeno rechazado');
$rules=['CODIGO:P002'=>$def,'CODIGO:I001'=>['estado'=>'INFORMATIVO','tipo_workbeat'=>'NUMERO','descripcion'=>'Cuota interna']];
$sc=$scope+['reglas'=>$rules];$dd=ncc_document($base,$sc);$aa=ncc_aggregate([$dd]);$ww=ncc_workbook($cols,$rows,$scope['rfc_emisor'],$rules);$wx=$ww['empleados'][$rfc];$xx=$aa['empleados'][$rfc];
ck(ncc_compare($ww['columnas'][0],$wx,$xx,$sc)['estado']==='COINCIDE','Motor aplica relación guardada');$inf=ncc_compare($ww['columnas'][4],$wx,$xx,$sc);ck($inf['estado']==='NO_DISPONIBLE_XML'&&$inf['workbeat']===70.0&&$inf['xml']===null&&$inf['diferencia']===null,'Informativo conserva dato sin falsa conciliación');
$cc=$cols;$cc[0]['estado_al_importar']='AMBIGUO';ck(ncc_workbook($cc,$rows,$scope['rfc_emisor'],$rules)['columnas'][0]['plan']['modo']==='pendiente','Reglas no resuelven columnas duplicadas arbitrariamente');
$pending=ncm_plan($w['columnas'][0]['plan'],['estado'=>'PENDIENTE','tipo_workbeat'=>'NUMERO','descripcion'=>'Revisar']);ck($pending['modo']==='pendiente','Se puede suspender una equivalencia');ck(ncm_plan($pending,['estado'=>'PREDETERMINADO'])===$pending,'Predeterminado no transforma el plan base');
// Los números repetidos (salario/tasa) se comparan una vez, sin sumarlos.
$unique=$yearRule;$unique['operacion']='NUMERO_UNICO';$unique['terminos']=[['selector'=>selector_for($dis,'Comprobante@Total')['selector'],'signo'=>1]];
$ur=['ENCABEZADO:SALARIO'=>$unique];$uc=[['indice'=>0,'letra'=>'A','encabezado'=>'Salario','clave_campo'=>'ENCABEZADO:SALARIO','estado_al_importar'=>'ACTIVO']];$urows=[['renglon'=>5,'clase'=>'EMPLEADO','numero_empleado'=>'0010','rfc'=>$rfc,'valores'=>[140]],['renglon'=>6,'clase'=>'ADICIONAL','numero_empleado'=>'0010','rfc'=>$rfc,'valores'=>['140.0000']]];
$us=$scope+['reglas'=>$ur];$ud=ncc_document($base,$us);$ua=ncc_aggregate([$ud]);$uw=ncc_workbook($uc,$urows,$scope['rfc_emisor'],$ur);ck(ncc_compare($uw['columnas'][0],$uw['empleados'][$rfc],$ua['empleados'][$rfc],$us)['estado']==='COINCIDE','Número repetido no se acumula');$urows[1]['valores'][0]=141;$uw=ncc_workbook($uc,$urows,$scope['rfc_emisor'],$ur);ck(ncc_compare($uw['columnas'][0],$uw['empleados'][$rfc],$ua['empleados'][$rfc],$us)['estado']==='DATOS_MULTIPLES','Número único cambiante requiere revisión');
// Persistencia en memoria: el adaptador sólo omite FOR UPDATE de MySQL para SQLite.
class NcmTestPDO extends PDO {public function prepare(string $query,array $options=[]):PDOStatement|false{return parent::prepare(str_replace(' FOR UPDATE','',$query),$options);}}
$pdo=new NcmTestPDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);ck(!ncm_schema($pdo,false),'Sin migración usa reglas anteriores');
$pdo->exec('CREATE TABLE nomina_campos(id_campo INTEGER PRIMARY KEY AUTOINCREMENT,id_empresa INTEGER,clave_hash TEXT,clave_campo TEXT,encabezado TEXT,tipo_valor TEXT,estado TEXT,id_usuario_alta INTEGER,fecha_alta TEXT,fecha_deteccion TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(id_empresa,clave_hash))');
$pdo->exec('CREATE TABLE nomina_config_xml_muestras(id_muestra INTEGER PRIMARY KEY AUTOINCREMENT,id_empresa INTEGER,hash_archivo TEXT,nombre_archivo TEXT,uuid TEXT,rfc_receptor TEXT,fecha_pago TEXT,xml_texto TEXT,id_usuario INTEGER,fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(id_empresa,hash_archivo));CREATE TABLE nomina_config_xml_campos(id_xml_campo INTEGER PRIMARY KEY AUTOINCREMENT,id_empresa INTEGER,selector_hash TEXT,selector_json TEXT,etiqueta TEXT,ejemplos_json TEXT,tipo_sugerido TEXT,id_muestra INTEGER,UNIQUE(id_empresa,selector_hash));CREATE TABLE nomina_config_reglas(id_regla INTEGER PRIMARY KEY AUTOINCREMENT,id_empresa INTEGER,id_campo INTEGER,version_regla INTEGER,definicion_json TEXT,id_usuario INTEGER,comentario TEXT,fecha_actualizacion TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(id_empresa,id_campo));CREATE TABLE nomina_config_reglas_historial(id_regla INTEGER,version_regla INTEGER,definicion_json TEXT,id_usuario INTEGER,comentario TEXT,fecha_registro TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id_regla,version_regla))');ck(ncm_schema($pdo),'Migración disponible');
$pdo->beginTransaction();$reg=nf_fields($pdo,1,$cols,true,1);$s1=ncm_store_xml($pdo,1,1,'normal.xml',$xml,$scope['rfc_emisor']);$pdo->commit();$count=(int)$pdo->query('SELECT COUNT(*) FROM nomina_config_xml_campos')->fetchColumn();ck($count===count($dis),'Registro dinámico completo');
$pdo->beginTransaction();$s2=ncm_store_xml($pdo,1,1,'repetido.xml',$xml,$scope['rfc_emisor']);$s3=ncm_store_xml($pdo,1,1,'otro_prefijo.xml',$prefix,$scope['rfc_emisor']);$pdo->commit();ck($s1['id_muestra']===$s2['id_muestra']&&$s2['campos_nuevos']===0&&$s3['campos_nuevos']===0,'Sin duplicar muestras/campos por prefijo');
$q=$pdo->prepare('SELECT id_xml_campo FROM nomina_config_xml_campos WHERE selector_hash=?');$q->execute([$g['hash']]);$gid=(int)$q->fetchColumn();$q->execute([$ex['hash']]);$eid=(int)$q->fetchColumn();
$input=['estado'=>'RELACIONADO','tipo_workbeat'=>'NUMERO','operacion'=>'SUMA','ausencia'=>'CERO','terminos'=>[['id_xml_campo'=>$gid,'signo'=>1],['id_xml_campo'=>$eid,'signo'=>1]]];$definition=ncm_definition($pdo,1,$input);ck(ncm_probe($pdo,1,$definition,[$s1['id_muestra']])['apta'],'Prueba antes de guardar');
rejected(fn()=>ncm_definition($pdo,2,$input),'Selector de otra empresa rechazado');rejected(fn()=>ncm_probe($pdo,2,$definition,[$s1['id_muestra']]),'Muestra ajena rechazada');$dupe=$input;$dupe['terminos'][1]=$dupe['terminos'][0];rejected(fn()=>ncm_definition($pdo,1,$dupe),'No sumar mismo campo dos veces');
$invalidOp=$input;$invalidOp['operacion']='eval';rejected(fn()=>ncm_definition($pdo,1,$invalidOp),'Sin expresiones arbitrarias');$rootField=(int)$pdo->query("SELECT id_xml_campo FROM nomina_config_xml_campos WHERE etiqueta='Comprobante@Total'")->fetchColumn();$rootInput=$input;$rootInput['terminos']=[['id_xml_campo'=>$rootField,'signo'=>1]];rejected(fn()=>ncm_definition($pdo,1,$rootInput),'Total obligatorio ausente no permite cero');
$id=(int)$reg['columnas'][0]['id_campo'];$pdo->beginTransaction();ck(ncm_save($pdo,1,1,$id,0,$definition,'Validado con ejemplo')===1,'Primera versión');$pdo->commit();$snapshot=ncm_load($pdo,1);ck($snapshot['CODIGO:P002']['revision']===1,'Recuperar versión y regla');ck(ncm_load($pdo,2)===[],'Aislamiento reglas por empresa');
$pdo->beginTransaction();rejected(fn()=>ncm_save($pdo,1,1,$id,0,$definition,'Versión vieja'),'Concurrencia optimista');$pdo->rollBack();
$info=ncm_definition($pdo,1,['estado'=>'INFORMATIVO','tipo_workbeat'=>'NUMERO']);ck(ncm_probe($pdo,1,$info,[])['apta'],'Informativo sin XML');$pdo->beginTransaction();ck(ncm_save($pdo,1,1,$id,1,$info,'No aparece en XML')===2,'Actualizar versión');$pdo->commit();ck((int)$pdo->query('SELECT COUNT(*) FROM nomina_config_reglas_historial')->fetchColumn()===2,'Historial conserva ambas versiones');ck($snapshot['CODIGO:P002']['estado']==='RELACIONADO'&&ncm_load($pdo,1)['CODIGO:P002']['estado']==='INFORMATIVO','Instantánea anterior inmutable');
$pdo->beginTransaction();rejected(fn()=>ncm_save($pdo,2,1,$id,2,$info,'Otro'),'Guardar campo ajeno rechazado');$pdo->rollBack();
// XLSX sintético para encabezados, sin almacenar empleados ni importes.
$tmp=tempnam(sys_get_temp_dir(),'ncm_test_');try{
 $zip=new XlsxSimpleWriter($tmp);$zip->addString('xl/workbook.xml','<workbook><sheets><sheet name="Nomina" r:id="r1"/></sheets></workbook>');$zip->addString('xl/_rels/workbook.xml.rels','<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/></Relationships>');$zip->addString('xl/worksheets/sheet1.xml','<worksheet><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>RFC</t></is></c><c r="B1" t="inlineStr"><is><t>P002 - Sueldos</t></is></c><c r="C1" t="inlineStr"><is><t>P777 - Nuevo</t></is></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>TEST010101AB1</t></is></c><c r="B2"><v>100</v></c><c r="C2"><v>5</v></c></row></sheetData></worksheet>');$zip->close();
 $parsed=ncm_excel($tmp,'xlsx');ck($parsed['fila_encabezado']===1&&count($parsed['columnas'])===3,'Reconocer encabezados XLSX');ck($parsed['columnas'][1]['ejemplos']===[100],'Ejemplos valores');$before=(int)$pdo->query('SELECT COUNT(*) FROM nomina_campos')->fetchColumn();nf_fields($pdo,1,$parsed['columnas']);ck((int)$pdo->query('SELECT COUNT(*) FROM nomina_campos')->fetchColumn()===$before,'Analizar no registra');nf_fields($pdo,1,$parsed['columnas'],true,1);$after=(int)$pdo->query('SELECT COUNT(*) FROM nomina_campos')->fetchColumn();nf_fields($pdo,1,array_reverse($parsed['columnas']),true,1);ck((int)$pdo->query('SELECT COUNT(*) FROM nomina_campos')->fetchColumn()===$after,'Columnas movidas no duplican catálogo');
 $raw=file_get_contents($tmp);$off=strpos($raw,'<worksheet>');$raw[$off]='!';file_put_contents($tmp,$raw);rejected(fn()=>ncm_excel($tmp,'xlsx'),'XLSX CRC corrupto rechazado');
}finally{unlink($tmp);}
echo "OK: $checks comprobaciones de configuración dinámica, reglas, empresa, versiones y XLSX.\n";
