<?php
session_start();
require_once '../config/db.php';require_once '../includes/seguridad.php';seguridad_exigir_sesion($pdo,true);require_once '../includes/permisos_documentos.php';require_once '../includes/oracle_iva_conciliacion.php';require_once '../includes/XlsxSimpleWriter.php';
function oixe($s){return htmlspecialchars((string)$s,ENT_QUOTES|ENT_XML1,'UTF-8');}
function oix_col($n){$s='';while($n>0){$n--; $s=chr(65+($n%26)).$s; $n=intdiv($n,26);}return $s;}
function oix_cell($ref,$v,$num=false){if($num)return '<c r="'.$ref.'"><v>'.(is_numeric($v)?(0+$v):0).'</v></c>';return '<c r="'.$ref.'" t="inlineStr"><is><t xml:space="preserve">'.oixe($v).'</t></is></c>';}
function oix_sheet(array $headers,array $rows): string{$x='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';$r=1;$x.='<row r="1">';foreach($headers as $i=>$h)$x.=oix_cell(oix_col($i+1).'1',$h);$x.='</row>';foreach($rows as $row){$r++;$x.='<row r="'.$r.'">';foreach(array_values($row) as $i=>$v)$x.=oix_cell(oix_col($i+1).$r,$v,is_int($v)||is_float($v));$x.='</row>';}$x.='</sheetData><autoFilter ref="A1:'.oix_col(max(1,count($headers))).max(1,$r).'"/></worksheet>';return $x;}
try{
 $u=(int)($_SESSION['id_usuario']??0);$e=(int)($_SESSION['id_empresa']??0);exigir_permiso_accion($pdo,$u,$e,'oracle_pagos');oic_tables($pdo);$id=(int)($_GET['id_conciliacion']??0);
 $st=$pdo->prepare('SELECT resultado_json,anio,mes FROM oracle_iva_conciliaciones WHERE id_conciliacion=? AND id_empresa=?');$st->execute([$id,$e]);$rec=$st->fetch(PDO::FETCH_ASSOC);if(!$rec)throw new RuntimeException('Conciliación no encontrada.');$r=json_decode((string)$rec['resultado_json'],true);if(!is_array($r))throw new RuntimeException('Resultado inválido.');
 $sheets=[];
 $imp=[];foreach(($r['importados_oracle']??[]) as $x)$imp[]=[($x['hoja']??''),($x['renglon_excel']??''),($x['cuenta']??''),($x['cuenta_descripcion']??''),($x['cuenta_tipo']??''),($x['fecha_contable']??''),($x['origen']??''),($x['categoria']??''),($x['clase_evento']??''),($x['numero_transaccion']??''),($x['descripcion']??''),($x['debito']??0),($x['credito']??0),($x['neto']??0),($x['referencia_factura']??''),($x['tipo_referencia']??''),($x['concilio']??''),($x['estado_conciliacion']??'')];
 $sheets[]=['IMPORTADO ORACLE',['Hoja','Renglón','Cuenta','Descripción cuenta','Tipo cuenta','Fecha contable','Origen','Categoría','Clase evento','Número transacción','Descripción línea','Débito','Crédito','Neto','Referencia detectada','Tipo referencia','Concilió','Estado conciliación'],$imp];
 $rr=$r['resumen']??[];$sheets[]=['RESUMEN',['Concepto','Valor'],[['Débito Oracle',$rr['oracle_debito']??0],['Crédito Oracle',$rr['oracle_credito']??0],['Neto Oracle',$rr['oracle_neto']??0],['IVA Visor',$rr['visor_iva']??0],['Diferencia global',$rr['diferencia_global']??0],['Conciliados',$rr['conciliados']??0],['Diferencias',$rr['diferencias']??0],['Oracle sin conciliar',$rr['oracle_sin_conciliar']??0],['Visor sin conciliar',$rr['visor_sin_conciliar']??0],['EXP',$rr['exp']??0]]];
 $mk=function(array $arr){$out=[];foreach($arr as $x)$out[]=[($x['referencia']??''),($x['tipo']??''),($x['regla']??''),($x['descripcion']??''),($x['debito']??0),($x['credito']??0),($x['oracle']??0),($x['visor']??0),($x['diferencia']??0),($x['estado']??''),($x['transacciones']??'')];return $out;};
 $heads=['Referencia','Tipo','Regla','Descripción Oracle','Débito','Crédito','IVA Oracle neto','IVA Visor','Diferencia','Estado','Transacciones'];
 $sheets[]=['CONCILIADOS',$heads,$mk($r['conciliados']??[])];$sheets[]=['DIFERENCIAS',$heads,$mk($r['diferencias']??[])];$sheets[]=['ORACLE SIN CONC',$heads,$mk($r['oracle_sin_conciliar']??[])];$sheets[]=['EXP',$heads,$mk($r['exp']??[])];
 $vs=[];foreach(($r['visor_sin_conciliar']??[]) as $x)$vs[]=[($x['uuid']??''),($x['rfc']??''),($x['nombre']??''),trim(($x['serie']??'').' '.($x['folio']??'')),($x['fecha_emision']??''),($x['fecha_fiscal']??''),($x['ref_pago']??''),($x['base_iva']??0),($x['iva']??0)];
 $sheets[]=['VISOR SIN CONC',['UUID','RFC','Proveedor','Factura','Fecha emisión','Fecha fiscal','Ref pago','Base IVA','IVA'],$vs];
 $trAnt=[];$trSig=[];foreach(($r['transito']??[]) as $x){$fila=[($x['grupo']??''),($x['uuid']??''),($x['proveedor']??''),($x['iva']??0),($x['esperado']??''),!empty($x['oracle_aplico'])?'SÍ':'NO',($x['estado']??''),($x['referencia_oracle']??'')];$g=strtoupper((string)($x['grupo']??''));if(strpos($g,'MES ANTERIOR')===0)$trAnt[]=$fila;elseif(strpos($g,'TRÁNSITO A MES POSTERIOR')===0||strpos($g,'TRANSITO A MES POSTERIOR')===0)$trSig[]=$fila;}
 $sheets[]=['TRANSITO ANTERIOR',['Grupo','UUID','Proveedor','IVA','Esperado Oracle','Aplicó Oracle','Estado','Referencia Oracle'],$trAnt];
 $sheets[]=['TRANSITO SIGUIENTE',['Grupo','UUID','Proveedor','IVA','Esperado Oracle','Aplicó Oracle','Estado','Referencia Oracle'],$trSig];
 $expDet=[];foreach(($r['exp']??[]) as $g)foreach(($g['detalles']??[]) as $d)$expDet[]=[($g['referencia']??''),($d['uuid']??''),($d['rfc']??''),($d['nombre']??''),trim(($d['serie']??'').' '.($d['folio']??'')),($d['ref_pago']??''),($d['iva']??0)];
 $sheets[]=['DETALLE EXP',['EXP','UUID','RFC','Proveedor','Factura','Ref pago','IVA'],$expDet];
 $tmp=tempnam(sys_get_temp_dir(),'oic_xlsx_');if(!$tmp)throw new RuntimeException('No se pudo crear temporal.');$zip=new XlsxSimpleWriter($tmp);
 $types='<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>';
 $wb='<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>';$rels='<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">';
 foreach($sheets as $i=>$sh){$n=$i+1;$name=substr(preg_replace('/[\\\/\?\*\[\]:]/',' ',(string)$sh[0]),0,31);$wb.='<sheet name="'.oixe($name).'" sheetId="'.$n.'" r:id="rId'.$n.'"/>';$rels.='<Relationship Id="rId'.$n.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'.$n.'.xml"/>';$types.='<Override PartName="/xl/worksheets/sheet'.$n.'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';$zip->addString('xl/worksheets/sheet'.$n.'.xml',oix_sheet($sh[1],$sh[2]));}
 $wb.='</sheets></workbook>';$rels.='</Relationships>';$types.='</Types>';$zip->addString('[Content_Types].xml',$types);$zip->addString('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');$zip->addString('xl/workbook.xml',$wb);$zip->addString('xl/_rels/workbook.xml.rels',$rels);$zip->close();unset($zip);
 $name='CONCILIACION_IVA_ORACLE_'.$rec['anio'].'_'.sprintf('%02d',(int)$rec['mes']).'.xlsx';while(ob_get_level()>0)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$name.'"');header('Content-Length: '.filesize($tmp));readfile($tmp);@unlink($tmp);
}catch(Throwable $x){http_response_code(400);header('Content-Type:text/plain; charset=utf-8');echo 'No se pudo exportar: '.$x->getMessage();}
