<?php
session_start(); header('Content-Type: application/json; charset=utf-8'); set_time_limit(0);
require_once __DIR__.'/../config/db.php'; require_once __DIR__.'/../includes/seguridad.php';
require_once __DIR__ . '/../includes/permisos_documentos.php';
seguridad_exigir_sesion($pdo,true); exigir_permiso_accion($pdo,(int)($_SESSION['id_usuario']??0),(int)($_SESSION['id_empresa']??0),'consulta_sat_69'); $uid=(int)($_SESSION['id_usuario']??0); session_write_close();
const SAT69_BASE='https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos/Documents_AGR/';
function out69($a,$h=200){http_response_code($h);echo json_encode($a,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE);exit;}
function tables69(PDO $p){
$p->exec("CREATE TABLE IF NOT EXISTS sat_69_contribuyentes(id_69 bigint unsigned NOT NULL AUTO_INCREMENT,rfc varchar(20) NOT NULL,nombre_contribuyente varchar(500) NOT NULL,tipo_publicacion varchar(120) NOT NULL,nivel_riesgo varchar(20) NOT NULL DEFAULT 'INFORMATIVO',fecha_publicacion varchar(100) DEFAULT NULL,detalle_resumen text DEFAULT NULL,datos_json longtext DEFAULT NULL,fuente_archivo varchar(255) NOT NULL,fecha_sincronizacion datetime NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(id_69),KEY idx_69_rfc(rfc),KEY idx_69_tipo(tipo_publicacion),KEY idx_69_riesgo(nivel_riesgo),KEY idx_69_nombre(nombre_contribuyente(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$p->exec("CREATE TABLE IF NOT EXISTS sat_69_staging(id_staging bigint unsigned NOT NULL AUTO_INCREMENT,id_proceso varchar(64) NOT NULL,rfc varchar(20) NOT NULL,nombre_contribuyente varchar(500) NOT NULL,tipo_publicacion varchar(120) NOT NULL,nivel_riesgo varchar(20) NOT NULL,fecha_publicacion varchar(100) DEFAULT NULL,detalle_resumen text DEFAULT NULL,datos_json longtext DEFAULT NULL,fuente_archivo varchar(255) NOT NULL,PRIMARY KEY(id_staging),KEY idx_69s_proc(id_proceso),KEY idx_69s_rfc(rfc)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$p->exec("CREATE TABLE IF NOT EXISTS sat_69_control(id_control tinyint NOT NULL,fuente_url varchar(500) NOT NULL,leyenda_actualizacion varchar(255) DEFAULT NULL,fecha_sincronizacion datetime NOT NULL,total_registros int NOT NULL DEFAULT 0,archivos_procesados int NOT NULL DEFAULT 0,PRIMARY KEY(id_control)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$p->exec("CREATE TABLE IF NOT EXISTS sat_69_procesos(id_proceso varchar(64) NOT NULL,id_usuario int NOT NULL,estado varchar(20) NOT NULL DEFAULT 'pendiente',etapa varchar(120) NOT NULL DEFAULT 'Preparando',porcentaje tinyint unsigned NOT NULL DEFAULT 0,registros_procesados int NOT NULL DEFAULT 0,total_registros int NOT NULL DEFAULT 0,cancelar tinyint NOT NULL DEFAULT 0,mensaje varchar(500) DEFAULT NULL,fecha_inicio datetime NOT NULL DEFAULT current_timestamp(),fecha_actualizacion datetime NOT NULL DEFAULT current_timestamp(),fecha_fin datetime DEFAULT NULL,PRIMARY KEY(id_proceso),KEY idx_69proc_user(id_usuario),KEY idx_69proc_estado(estado)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
function upd69(PDO $p,$id,$estado,$etapa,$pct,$proc=0,$tot=0,$msg=null,$fin=false){$s=$p->prepare("UPDATE sat_69_procesos SET estado=?,etapa=?,porcentaje=?,registros_procesados=?,total_registros=?,mensaje=?,fecha_actualizacion=NOW()".($fin?',fecha_fin=NOW()':'')." WHERE id_proceso=?");$s->execute([$estado,$etapa,max(0,min(100,$pct)),$proc,$tot,$msg,$id]);}
function cancel69(PDO $p,$id){$s=$p->prepare('SELECT cancelar FROM sat_69_procesos WHERE id_proceso=?');$s->execute([$id]);return (int)$s->fetchColumn()===1;}
function norm69($s){$s=trim((string)$s);$s=preg_replace('/^\\xEF\\xBB\\xBF/','',$s);$x=@iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$s);return strtoupper(preg_replace('/[^A-Z0-9]+/','_',($x!==false?$x:$s)));}
function utf69($s){if(mb_check_encoding($s,'UTF-8'))return trim($s);foreach(['Windows-1252','ISO-8859-1'] as $e){$x=@mb_convert_encoding($s,'UTF-8',$e);if($x!==false)return trim($x);}return trim($s);}
function download69($url,$file){$fp=fopen($file,'wb');if(!$fp)throw new RuntimeException('No se pudo crear temporal.');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_FILE=>$fp,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>25,CURLOPT_TIMEOUT=>240,CURLOPT_USERAGENT=>'SGKSAT-Articulo69/1.0',CURLOPT_SSL_VERIFYPEER=>true]);$ok=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);fclose($fp);if(!$ok||$code<200||$code>=300||!is_file($file)||filesize($file)<5)throw new RuntimeException("Descarga falló HTTP $code $err");}
function parse69(PDO $p,$id,$cfg,$file,&$count){
 $fh=fopen($file,'rb');if(!$fh)throw new RuntimeException('No se pudo abrir '.$cfg['file']);$sample=fgets($fh);rewind($fh);$semi=substr_count((string)$sample,';');$comma=substr_count((string)$sample,',');$del=$semi>$comma?';':',';$header=null;$idxR=-1;$idxN=-1;$idxF=-1;$line=0;
 $ins=$p->prepare("INSERT INTO sat_69_staging(id_proceso,rfc,nombre_contribuyente,tipo_publicacion,nivel_riesgo,fecha_publicacion,detalle_resumen,datos_json,fuente_archivo) VALUES(?,?,?,?,?,?,?,?,?)");
 while(($row=fgetcsv($fh,0,$del,'"','\\'))!==false){$line++;$row=array_map('utf69',$row);if(!$header){$n=array_map('norm69',$row);foreach($n as $i=>$h){if($idxR<0&&($h==='RFC'||str_contains($h,'RFC'))) $idxR=$i;if($idxN<0&&(str_contains($h,'RAZON_SOCIAL')||str_contains($h,'NOMBRE')||str_contains($h,'CONTRIBUYENTE'))) $idxN=$i;if($idxF<0&&str_contains($h,'FECHA'))$idxF=$i;}if($idxR>=0){$header=$row;continue;}if($line<20)continue;throw new RuntimeException('No se encontró encabezado RFC en '.$cfg['file']);}
   $rfc=strtoupper(preg_replace('/\\s+/','',$row[$idxR]??''));if(!preg_match('/^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$/u',$rfc))continue;$nom=trim($row[$idxN]??'');if($nom==='')$nom='SIN NOMBRE EN ARCHIVO SAT';$fecha=$idxF>=0?trim($row[$idxF]??''):null;$obj=[];foreach($header as $i=>$h){$h=trim($h);if($h!==''&&isset($row[$i])&&trim($row[$i])!=='')$obj[$h]=trim($row[$i]);}$parts=[];foreach($obj as $k=>$v){if(count($parts)>=5)break;if($v!==$rfc&&$v!==$nom)$parts[]=$k.': '.$v;}$det=implode(' | ',$parts);$ins->execute([$id,$rfc,$nom,$cfg['tipo'],$cfg['riesgo'],$fecha,$det,json_encode($obj,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE),$cfg['file']]);$count++;if(($count%500)===0){if(cancel69($p,$id))throw new RuntimeException('__CANCELADO__');upd69($p,$id,'ejecutando','Leyendo '.$cfg['tipo'],45,min($count,999999),0,$count.' registros leídos');}}
 fclose($fh);
}
function run69(PDO $p,$id){
 $files=[
 ['file'=>'Cancelados.csv','url'=>SAT69_BASE.'Cancelados.csv','tipo'=>'Cancelados','riesgo'=>'MEDIO'],
 ['file'=>'ReduccionArt74CFF.csv','url'=>SAT69_BASE.'ReduccionArt74CFF.csv','tipo'=>'Reducción de multas Art. 74','riesgo'=>'INFORMATIVO'],
 ['file'=>'Condonadosart146BCFF.csv','url'=>'https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos/Cifras_SAT/Indef/Condonadosart146BCFF.csv','tipo'=>'Condonados concurso mercantil Art. 146-B','riesgo'=>'INFORMATIVO'],
 ['file'=>'Condonadosart21CFF.csv','url'=>'https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos/Cifras_SAT/Indef/Condonadosart21CFF.csv','tipo'=>'Reducción de recargos Art. 21','riesgo'=>'INFORMATIVO'],
 ['file'=>'CondonadosporDecreto.csv','url'=>'https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos/Cifras_SAT/Indef/CondonadosporDecreto.csv','tipo'=>'Condonados por decreto','riesgo'=>'INFORMATIVO'],
 ['file'=>'Condonados_07_15.csv','url'=>'https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos/Cifras_SAT/Indef/Condonados_07_15.csv','tipo'=>'Condonados 2007-2015','riesgo'=>'INFORMATIVO'],
 ['file'=>'Cancelados_07_15.csv','url'=>'https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos/Cifras_SAT/Indef/Cancelados_07_15.csv','tipo'=>'Cancelados Art. 146-A 2007-2015','riesgo'=>'MEDIO'],
 ['file'=>'Retornoinversiones.csv','url'=>'https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos/Cifras_SAT/Indef/Retornoinversiones.csv','tipo'=>'Retorno de inversiones','riesgo'=>'INFORMATIVO'],
 ['file'=>'Exigibles.csv','url'=>SAT69_BASE.'Exigibles.csv','tipo'=>'Créditos exigibles','riesgo'=>'ALTO'],
 ['file'=>'Firmes.csv','url'=>SAT69_BASE.'Firmes.csv','tipo'=>'Créditos firmes','riesgo'=>'ALTO'],
 ['file'=>'No_localizados.csv','url'=>SAT69_BASE.'No_localizados.csv','tipo'=>'No localizados','riesgo'=>'ALTO'],
 ['file'=>'Sentencias.csv','url'=>SAT69_BASE.'Sentencias.csv','tipo'=>'Sentencias condenatorias','riesgo'=>'ALTO'],
 ['file'=>'CSDsinefectos.csv','url'=>SAT69_BASE.'CSDsinefectos.csv','tipo'=>'CSD sin efectos','riesgo'=>'ALTO'],
 ['file'=>'EntespublicosydeGobiernoomisos.csv','url'=>SAT69_BASE.'EntespublicosydeGobiernoomisos.csv','tipo'=>'Entes públicos y gobierno omisos','riesgo'=>'ALTO']];
 $p->prepare('DELETE FROM sat_69_staging WHERE id_proceso=?')->execute([$id]);$count=0;$ok=0;$tmp=[];$n=count($files);
 foreach($files as $i=>$cfg){if(cancel69($p,$id))throw new RuntimeException('__CANCELADO__');$pct=5+(int)floor(($i/$n)*55);upd69($p,$id,'ejecutando','Descargando '.$cfg['tipo'],$pct,$count,0,$cfg['file']);$f=tempnam(sys_get_temp_dir(),'sat69_');$tmp[]=$f;try{download69($cfg['url'],$f);parse69($p,$id,$cfg,$f,$count);$ok++;}catch(Throwable $e){if($e->getMessage()==='__CANCELADO__')throw $e;/* algunos nombres históricos pueden no existir; continúa y exige al menos listas de riesgo */}}
 if($ok<5||$count<1)throw new RuntimeException('No se obtuvieron suficientes archivos oficiales del SAT. Archivos leídos: '.$ok);
 upd69($p,$id,'ejecutando','Aplicando catálogo local',88,$count,$count,'Reemplazando catálogo anterior');$p->beginTransaction();$p->exec('DELETE FROM sat_69_contribuyentes');$st=$p->prepare("INSERT INTO sat_69_contribuyentes(rfc,nombre_contribuyente,tipo_publicacion,nivel_riesgo,fecha_publicacion,detalle_resumen,datos_json,fuente_archivo,fecha_sincronizacion) SELECT rfc,nombre_contribuyente,tipo_publicacion,nivel_riesgo,fecha_publicacion,detalle_resumen,datos_json,fuente_archivo,NOW() FROM sat_69_staging WHERE id_proceso=?");$st->execute([$id]);$ctl=$p->prepare("INSERT INTO sat_69_control(id_control,fuente_url,leyenda_actualizacion,fecha_sincronizacion,total_registros,archivos_procesados) VALUES(1,?,'Listado oficial artículo 69 CFF',NOW(),?,?) ON DUPLICATE KEY UPDATE fuente_url=VALUES(fuente_url),leyenda_actualizacion=VALUES(leyenda_actualizacion),fecha_sincronizacion=NOW(),total_registros=VALUES(total_registros),archivos_procesados=VALUES(archivos_procesados)");$ctl->execute([SAT69_BASE,$count,$ok]);$p->commit();$p->prepare('DELETE FROM sat_69_staging WHERE id_proceso=?')->execute([$id]);foreach($tmp as $f)@unlink($f);upd69($p,$id,'completado','Terminado',100,$count,$count,"Artículo 69 actualizado: $count registros en $ok archivos.",true);
}
try{tables69($pdo);$a=strtolower(trim((string)($_POST['accion']??$_GET['accion']??'iniciar')));
 if($a==='iniciar'){$active=$pdo->query("SELECT id_proceso FROM sat_69_procesos WHERE estado IN('pendiente','ejecutando') ORDER BY fecha_inicio DESC LIMIT 1")->fetchColumn();if($active)out69(['status'=>'busy','msg'=>'Ya existe sincronización 69 en proceso.','id_proceso'=>$active],409);$id=bin2hex(random_bytes(16));$pdo->prepare("INSERT INTO sat_69_procesos(id_proceso,id_usuario,estado,etapa,porcentaje,mensaje) VALUES(?,?,'pendiente','Preparando',1,'Proceso creado')")->execute([$id,$uid]);out69(['status'=>'ok','id_proceso'=>$id]);}
 $id=trim((string)($_POST['id_proceso']??$_GET['id_proceso']??''));if($id==='')out69(['status'=>'error','msg'=>'Falta id_proceso'],400);$s=$pdo->prepare('SELECT id_proceso FROM sat_69_procesos WHERE id_proceso=? AND id_usuario=?');$s->execute([$id,$uid]);if(!$s->fetchColumn())out69(['status'=>'error','msg'=>'Proceso no encontrado'],404);
 if($a==='estado'){$s=$pdo->prepare('SELECT * FROM sat_69_procesos WHERE id_proceso=?');$s->execute([$id]);out69(['status'=>'ok','proceso'=>$s->fetch(PDO::FETCH_ASSOC)]);}if($a==='cancelar'){$pdo->prepare("UPDATE sat_69_procesos SET cancelar=1,mensaje='Cancelación solicitada' WHERE id_proceso=? AND estado IN('pendiente','ejecutando')")->execute([$id]);out69(['status'=>'ok']);}
 if($a==='ejecutar'){$s=$pdo->prepare("UPDATE sat_69_procesos SET estado='ejecutando',etapa='Iniciando',porcentaje=3 WHERE id_proceso=? AND estado='pendiente'");$s->execute([$id]);if(!$s->rowCount())out69(['status'=>'error','msg'=>'Proceso ya iniciado'],409);try{run69($pdo,$id);out69(['status'=>'ok']);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$pdo->prepare('DELETE FROM sat_69_staging WHERE id_proceso=?')->execute([$id]);if($e->getMessage()==='__CANCELADO__'||cancel69($pdo,$id)){upd69($pdo,$id,'cancelado','Cancelado',0,0,0,'Proceso cancelado; se conservó el catálogo anterior.',true);out69(['status'=>'cancelado']);}upd69($pdo,$id,'error','Error',0,0,0,'No se pudo sincronizar: '.$e->getMessage(),true);seguridad_log_error($e,'sincronizar_sat_69');out69(['status'=>'error','msg'=>$e->getMessage()],500);}}
 out69(['status'=>'error','msg'=>'Acción no válida'],400);
}catch(Throwable $e){seguridad_log_error($e,'sincronizar_sat_69_general');out69(['status'=>'error','msg'=>$e->getMessage()],500);}
