<?php session_start();require_once __DIR__.'/../config/db.php';require_once __DIR__.'/../includes/seguridad.php';require_once __DIR__.'/../includes/permisos_documentos.php';seguridad_exigir_sesion($pdo,true);try{exigir_permiso_accion($pdo,(int)($_SESSION['id_usuario']??0),(int)($_SESSION['id_empresa']??0),'consulta_alertas_69');}catch(Throwable $e){echo '<div class="alert alert-danger">'.htmlspecialchars($e->getMessage()).'</div>';exit;}?>
<style>.a69-panel{background:#fff;border:1px solid #c9d8e5;border-radius:10px;padding:16px;color:#243746}.a69-cards{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:10px;margin-bottom:14px}.a69-card{border:1px solid #d7e2ea;border-radius:9px;padding:12px;background:#f8fbfd}.a69-card .n{font-size:1.55rem;font-weight:800}.a69-card .t{font-size:.73rem;color:#61788a}.a69-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.a69-toolbar .form-select{width:220px}.tabla-a69 th{background:#e9f2f8!important;color:#123f5d!important;white-space:nowrap;font-size:.76rem}.tabla-a69 td{font-size:.76rem;vertical-align:middle}@media(max-width:850px){.a69-cards{grid-template-columns:1fr 1fr}.a69-toolbar .form-select{width:100%}}</style>
<div class="a69-panel"><div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3"><div><h5><i class="bi bi-person-exclamation text-danger"></i> Emisores con riesgos del artículo 69</h5><div class="text-muted small">Cruce independiente de emisores contra los listados del artículo 69. No se mezcla con las alertas 69-B.</div></div><button class="btn btn-danger btn-sm" id="btnCruzar69"><i class="bi bi-arrow-repeat"></i> Cruzar emisores ahora</button></div><div class="a69-cards"><div class="a69-card"><div class="n text-danger" id="a69Alto">0</div><div class="t">RIESGO ALTO</div></div><div class="a69-card"><div class="n text-warning" id="a69Nuevas">0</div><div class="t">NUEVAS</div></div><div class="a69-card"><div class="n text-primary" id="a69Vistas">0</div><div class="t">EN REVISIÓN</div></div><div class="a69-card"><div class="n text-success" id="a69Atendidas">0</div><div class="t">ATENDIDAS</div></div></div><div class="a69-toolbar"><select id="filtroTipoA69" class="form-select form-select-sm"><option value="">Todas las publicaciones</option></select><select id="filtroSeguimientoA69" class="form-select form-select-sm"><option value="">Todos los seguimientos</option><option value="NUEVA">Nuevas</option><option value="VISTA">En revisión</option><option value="ATENDIDA">Atendidas</option></select><div class="form-check ms-1"><input class="form-check-input" type="checkbox" id="soloRiesgoA69" checked><label class="form-check-label small">Solo riesgo alto/medio</label></div><button type="button" class="btn btn-success btn-sm ms-auto" id="btnExportarA69"><i class="bi bi-file-earmark-excel"></i> Exportar Excel</button></div><div class="table-responsive"><table id="tablaAlertas69" class="table table-striped table-hover table-bordered tabla-a69 w-100"><thead><tr><th>SEGUIMIENTO</th><th>EMPRESA</th><th>RFC</th><th>EMISOR</th><th>PUBLICACIÓN SAT</th><th>NIVEL</th><th>CFDI</th><th>IMPORTE CFDI</th><th>DETECTADO</th><th>ACCIONES</th></tr></thead></table></div></div>
<script>(function(){const esc=s=>$('<div>').text(s??'').html();const seg=v=>v==='NUEVA'?'<span class="badge bg-danger">NUEVA</span>':v==='VISTA'?'<span class="badge bg-primary">EN REVISIÓN</span>':'<span class="badge bg-success">ATENDIDA</span>';const pubs=v=>String(v||'').split(' | ').map(x=>`<span class="badge bg-secondary me-1">${esc(x)}</span>`).join('');const niv=v=>String(v||'').split(' | ').map(x=>`<span class="badge ${x==='ALTO'?'bg-danger':x==='MEDIO'?'bg-warning text-dark':'bg-secondary'} me-1">${esc(x)}</span>`).join('');const tabla=$('#tablaAlertas69').DataTable({destroy:true,scrollX:true,pageLength:25,order:[],ajax:{url:'ajax/listar_alertas_emisores_69.php',data:d=>{d.tipo=$('#filtroTipoA69').val();d.seguimiento=$('#filtroSeguimientoA69').val();d.solo_riesgo=$('#soloRiesgoA69').is(':checked')?1:0},dataSrc:r=>{if(!r.success){Swal.fire('Error',r.error||'Error','error');return[]}const x=r.resumen||{};$('#a69Alto').text(x.alto||0);$('#a69Nuevas').text(x.nuevas||0);$('#a69Vistas').text(x.vista||0);$('#a69Atendidas').text(x.atendidas||0);const vals=new Set();(r.data||[]).forEach(z=>String(z.publicaciones||'').split(' | ').forEach(q=>vals.add(q)));if($('#filtroTipoA69 option').length===1)[...vals].sort().forEach(q=>$('#filtroTipoA69').append(new Option(q,q)));return r.data||[]}},columns:[{data:'seguimiento',render:seg},{data:'empresa'},{data:'rfc',className:'fw-bold'},{data:'nombre_emisor'},{data:'publicaciones',render:pubs},{data:'niveles',render:niv},{data:'cfdi',className:'text-end'},{data:'total_cfdi',className:'text-end',render:v=>'$'+Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:2})},{data:'primera_deteccion'},{data:null,orderable:false,render:r=>`<button class="btn btn-outline-primary btn-sm det69"><i class="bi bi-eye"></i></button> ${r.seguimiento!=='ATENDIDA'?'<button class="btn btn-success btn-sm ok69"><i class="bi bi-check2-circle"></i></button>':'<button class="btn btn-outline-secondary btn-sm re69"><i class="bi bi-arrow-counterclockwise"></i></button>'}`}]});const reload=()=>tabla.ajax.reload(null,false);$('#filtroTipoA69,#filtroSeguimientoA69,#soloRiesgoA69').on('change',reload);$('#btnExportarA69').on('click',function(){const q=new URLSearchParams({tipo:$('#filtroTipoA69').val()||'',seguimiento:$('#filtroSeguimientoA69').val()||'',solo_riesgo:$('#soloRiesgoA69').is(':checked')?'1':'0',buscar:tabla.search()||''});window.location.href='ajax/exportar_alertas_emisores_69_excel.php?'+q.toString();});$('#btnCruzar69').on('click',function(){
 const b=$(this).prop('disabled',true);
 const jobId=(window.crypto&&crypto.randomUUID)?crypto.randomUUID():('sat69_'+Date.now()+'_'+Math.random().toString(36).slice(2));
 let timer=null,terminado=false,cancelando=false;
 const cerrarTimer=()=>{if(timer){clearInterval(timer);timer=null}};
 const pintar=j=>{
   const p=Math.max(0,Math.min(100,Number(j.porcentaje||0)));
   $('#satCruceBar').css('width',p+'%').attr('aria-valuenow',p).text(p+'%');
   $('#satCruceTexto').text(j.mensaje||'Procesando...');
   $('#satCruceConteo').text((j.procesados||0)+' de '+(j.total||0)+' emisores');
   if(j.estado==='cancelando'){$('#btnCancelarCruceSat').prop('disabled',true).html('<span class="spinner-border spinner-border-sm me-1"></span> Cancelando...')}
 };
 Swal.fire({
   title:'Cruzando emisores · Artículo 69',
   html:`<div class="text-start">
          <div id="satCruceTexto" class="small mb-2">Preparando cruce...</div>
          <div class="progress" style="height:24px"><div id="satCruceBar" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width:0%">0%</div></div>
          <div id="satCruceConteo" class="small text-muted mt-2">0 de 0 emisores</div>
          <div class="text-center mt-3"><button type="button" class="btn btn-danger btn-sm" style="display:inline-block!important;visibility:visible!important;opacity:1!important;background:#dc3545!important;color:#fff!important;border:1px solid #dc3545!important;min-width:145px" id="btnCancelarCruceSat"><i class="bi bi-x-circle"></i> Cancelar proceso</button></div>
          <div class="small text-muted mt-2">Si cancela, se revierte el cruce actual y no quedan datos parciales.</div>
         </div>`,
   showConfirmButton:false,allowOutsideClick:false,allowEscapeKey:false,
   didOpen:()=>{
     $('#btnCancelarCruceSat').on('click',function(){
       if(cancelando||terminado)return;
       cancelando=true;
       $(this).prop('disabled',true).html('<span class="spinner-border spinner-border-sm me-1"></span> Cancelando...');
       $('#satCruceTexto').text('Solicitando cancelación segura...');
       $.post('ajax/cancelar_cruce_sat.php',{job_id:jobId},null,'json').fail(x=>{
         cancelando=false;
         $('#btnCancelarCruceSat').prop('disabled',false).html('<i class="bi bi-x-circle"></i> Cancelar proceso');
         Swal.showValidationMessage((x.responseJSON&&x.responseJSON.error)||'No se pudo solicitar la cancelación.');
       });
     });
     timer=setInterval(()=>{$.getJSON('ajax/estado_cruce_sat.php',{job_id:jobId},r=>{if(r.success&&r.job)pintar(r.job)})},500);
   }
 });
 $.post('ajax/sincronizar_alertas_69.php',{job_id:jobId},r=>{
   terminado=true;cerrarTimer();Swal.close();
   if(r.success&&r.cancelled){
     Swal.fire('Cruce cancelado','No se guardaron cambios parciales.','info');
   }else if(r.success){
     Swal.fire('Cruce terminado',`Coincidencias: <b>${r.resumen.total_emisores||0}</b><br>Riesgo alto/medio: <b>${r.resumen.emisores_riesgo||0}</b>`,'success');
     reload();
   }else Swal.fire('Error',r.error||'No se pudo realizar el cruce.','error');
 },'json').fail(x=>{
   terminado=true;cerrarTimer();Swal.close();
   Swal.fire('Error',(x.responseJSON&&x.responseJSON.error)||'No se pudo realizar el cruce.','error');
 }).always(()=>b.prop('disabled',false));
});$('#tablaAlertas69').on('click','.det69',function(){const r=tabla.row($(this).closest('tr')).data();$.post('ajax/actualizar_alerta_emisor_69.php',{id_emisor:r.id_emisor,accion:'vista'});$.getJSON('ajax/detalle_alerta_emisor_69.php',{id_emisor:r.id_emisor},d=>{const sat=(d.sat||[]).map(x=>`<tr><td>${esc(x.tipo_publicacion)}</td><td>${niv(x.nivel_riesgo)}</td><td>${esc(x.fecha_publicacion||'')}</td><td>${esc(x.detalle_resumen||'')}</td></tr>`).join('');const cf=(d.cfdi||[]).map(x=>`<tr><td>${esc(x.uuid)}</td><td>${esc([x.serie,x.folio].filter(Boolean).join('-'))}</td><td>${esc(x.fecha_emision)}</td><td class="text-end">$${Number(x.total_xml||0).toLocaleString('es-MX',{minimumFractionDigits:2})}</td></tr>`).join('');Swal.fire({title:esc(d.emisor.nombre_emisor),width:'92%',html:`<div class="text-start"><b>Empresa:</b> ${esc(d.emisor.empresa)} &nbsp; <b>RFC:</b> ${esc(d.emisor.rfc)}<h6 class="mt-3">Coincidencias artículo 69</h6><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Publicación</th><th>Nivel</th><th>Fecha</th><th>Detalle</th></tr></thead><tbody>${sat}</tbody></table></div><h6>CFDI relacionados (${(d.cfdi||[]).length})</h6><div class="table-responsive" style="max-height:320px"><table class="table table-sm table-striped"><tbody>${cf}</tbody></table></div></div>`}).then(reload)})});$('#tablaAlertas69').on('click','.ok69',function(){const r=tabla.row($(this).closest('tr')).data();Swal.fire({title:'Marcar atendido',input:'textarea',showCancelButton:true}).then(x=>{if(x.isConfirmed)$.post('ajax/actualizar_alerta_emisor_69.php',{id_emisor:r.id_emisor,accion:'atendida',observaciones:x.value||''},reload,'json')})});$('#tablaAlertas69').on('click','.re69',function(){const r=tabla.row($(this).closest('tr')).data();$.post('ajax/actualizar_alerta_emisor_69.php',{id_emisor:r.id_emisor,accion:'reabrir'},reload,'json')})})();</script>
