<?php
session_start();require_once '../config/db.php';require_once '../includes/seguridad.php';seguridad_exigir_sesion($pdo,true);require_once '../includes/permisos_documentos.php';
$u=(int)($_SESSION['id_usuario']??0);$e=(int)($_SESSION['id_empresa']??0);exigir_permiso_accion($pdo,$u,$e,'oracle_pagos');$empresa=(string)($_SESSION['empresa_nombre']??'Empresa activa');if(session_status()===PHP_SESSION_ACTIVE)session_write_close();$anio=(int)date('Y');$mes=(int)date('n');
?>
<style>
.oic-card{background:#fff;border:1px solid #d9e2ec;border-radius:12px;color:#172b3a}.oic-kpi{background:#f7f9fc;border:1px solid #dce5ef;border-radius:10px;padding:12px}.oic-kpi b{font-size:1.15rem}.oic-table{font-size:.83rem}.oic-table td,.oic-table th{vertical-align:middle}.oic-pill{font-size:.72rem}.oic-exp-detail{background:#fbfcfe}.oic-tabs .nav-link{color:#3a5068}.oic-tabs .nav-link.active{font-weight:700;color:#0d6efd}.oic-scroll{max-height:560px;overflow:auto;border:1px solid #e7edf3;border-radius:8px}.oic-scroll table{margin-bottom:0}.oic-scroll thead th{position:sticky;top:0;z-index:5;background:#eaf2f8;box-shadow:0 1px 0 #cfd8e3}.oic-exp-list{max-height:590px;overflow:auto;padding-right:2px}.oic-exp-item{border:1px solid #dbe4ec;border-radius:10px;margin-bottom:8px;background:#fff;overflow:hidden}.oic-exp-head{width:100%;border:0;background:#f8fafc;padding:10px 12px;text-align:left;display:flex;align-items:center;justify-content:space-between;gap:12px}.oic-exp-head:hover{background:#eef5fb}.oic-exp-left{display:flex;align-items:center;gap:8px;min-width:0}.oic-exp-ref{font-weight:700}.oic-exp-arrow{transition:transform .18s ease}.oic-exp-head[aria-expanded="true"] .oic-exp-arrow{transform:rotate(90deg)}.oic-exp-totals{white-space:nowrap;font-size:.85rem}.oic-exp-body{border-top:1px solid #e5ebf0}.oic-exp-body .oic-scroll{max-height:320px;border:0;border-radius:0}
</style>
<div class="container-fluid">
 <div class="d-flex flex-wrap justify-content-between align-items-center mb-3 gap-2">
  <div><h4 class="mb-0"><i class="bi bi-balance-scale"></i> Conciliación IVA Oracle ↔ Visor</h4><div class="text-muted small">Empresa activa: <b><?=htmlspecialchars($empresa)?></b></div></div>
  <button class="btn btn-outline-secondary btn-sm" onclick="cargarModulo('oracle_pagos')"><i class="bi bi-arrow-left"></i> Oracle Pagos</button>
 </div>
 <div class="oic-card p-3 mb-3">
  <div class="row g-2 align-items-end">
   <div class="col-md-2"><label class="form-label">Año</label><input id="oicAnio" type="number" class="form-control" value="<?=$anio?>" min="2000" max="2100"></div>
   <div class="col-md-2"><label class="form-label">Mes</label><select id="oicMes" class="form-select"><?php foreach(['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'] as $i=>$n):?><option value="<?=$i+1?>" <?=$mes===$i+1?'selected':''?>><?=$n?></option><?php endforeach;?></select></div>
   <div class="col-md-4"><label class="form-label">Archivo Oracle IVA (.xlsx)</label><input id="oicArchivo" type="file" class="form-control" accept=".xlsx"></div>
   <div class="col-md-2"><button id="oicBtnSubir" class="btn btn-primary w-100"><i class="bi bi-cloud-upload"></i> Subir archivo</button></div>
   <div class="col-md-2"><button id="oicBtnConciliar" class="btn btn-success w-100"><i class="bi bi-intersect"></i> Conciliar mes</button></div>
  </div>
  <div class="row g-2 mt-1 align-items-end"><div class="col-md-8"><label class="form-label">Archivo cargado para el periodo</label><select id="oicSelArchivo" class="form-select"><option value="">-- seleccione --</option></select></div><div class="col-md-4 d-flex gap-2"><button id="oicRecargar" class="btn btn-outline-primary flex-fill"><i class="bi bi-arrow-clockwise"></i> Actualizar archivos</button><button id="oicExport" class="btn btn-outline-success flex-fill" disabled><i class="bi bi-file-earmark-excel"></i> Exportar</button></div></div>
  <div id="oicEstado" class="small text-muted mt-2">El importador detecta automáticamente dónde empiezan los datos y dónde están Débito/Crédito, aunque Oracle cambie los renglones o el orden de columnas.</div>
 </div>
 <div id="oicResultados" style="display:none">
  <div class="row g-2 mb-3" id="oicKpis"></div>
  <div class="oic-card p-2">
   <ul class="nav nav-tabs oic-tabs" id="oicTabs"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#oicImp">Importado Oracle</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#oicConc">Conciliados</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#oicDif">Diferencias</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#oicExp">EXP / Caja chica</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#oicTraAnt">Tránsito mes anterior</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#oicTraSig">Tránsito mes siguiente</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#oicOra">Solo Oracle</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#oicVis">Solo Visor</button></li></ul>
   <div class="tab-content pt-2"><div class="tab-pane fade show active" id="oicImp"></div><div class="tab-pane fade" id="oicConc"></div><div class="tab-pane fade" id="oicDif"></div><div class="tab-pane fade" id="oicExp"></div><div class="tab-pane fade" id="oicTraAnt"></div><div class="tab-pane fade" id="oicTraSig"></div><div class="tab-pane fade" id="oicOra"></div><div class="tab-pane fade" id="oicVis"></div></div>
  </div>
 </div>
</div>
<script>
(function(){let lastId=0;const $A=$('#oicAnio'),$M=$('#oicMes'),$S=$('#oicSelArchivo'),$E=$('#oicEstado');const money=n=>Number(n||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2});const esc=s=>$('<div>').text(s==null?'':String(s)).html();
 function archivos(){const a=$A.val(),m=$M.val();$S.html('<option value="">Cargando...</option>');$.getJSON('ajax/oracle_iva_archivos.php',{anio:a,mes:m}).done(r=>{let h='<option value="">-- seleccione --</option>';if(r.ok)(r.archivos||[]).forEach(x=>h+='<option value="'+x.id_archivo+'">#'+x.id_archivo+' - '+esc(x.nombre_original)+' ('+x.filas_importadas+' movimientos, '+x.fecha_subida+')</option>');$S.html(h);}).fail(x=>$S.html('<option value="">Error al cargar</option>'));}
 function importTabla(arr){let h='<div class="mb-2 small text-muted">Renglones del Excel del mes seleccionado. La columna <b>Concilió</b> indica si ese movimiento quedó amarrado con el detalle DIOT.</div><div class="oic-scroll table-responsive"><table class="table table-sm table-striped oic-table"><thead><tr><th>Hoja</th><th>Renglón</th><th>Cuenta</th><th>Tipo cuenta</th><th>Fecha</th><th>Origen</th><th>Categoría</th><th>Clase</th><th>Núm. transacción</th><th>Descripción</th><th class="text-end">Débito</th><th class="text-end">Crédito</th><th class="text-end">Neto</th><th>Referencia</th><th>Tipo ref.</th><th>Concilió</th><th>Estado</th></tr></thead><tbody>';if(!arr.length)h+='<tr><td colspan="17" class="text-center text-muted py-4">Sin movimientos importados para el mes</td></tr>';arr.forEach(x=>{let c=x.concilio==='SI'?'bg-success':(x.concilio==='NO'?'bg-danger':'bg-secondary');h+='<tr><td>'+esc(x.hoja)+'</td><td>'+esc(x.renglon_excel)+'</td><td>'+esc(x.cuenta)+'</td><td>'+esc(x.cuenta_tipo)+'</td><td>'+esc(x.fecha_contable)+'</td><td>'+esc(x.origen)+'</td><td>'+esc(x.categoria)+'</td><td>'+esc(x.clase_evento)+'</td><td>'+esc(x.numero_transaccion)+'</td><td style="min-width:320px">'+esc(x.descripcion)+'</td><td class="text-end">$'+money(x.debito)+'</td><td class="text-end">$'+money(x.credito)+'</td><td class="text-end">$'+money(x.neto)+'</td><td><b>'+esc(x.referencia_factura)+'</b></td><td>'+esc(x.tipo_referencia)+'</td><td><span class="badge '+c+'">'+esc(x.concilio)+'</span></td><td>'+esc(x.estado_conciliacion)+'</td></tr>';});return h+'</tbody></table></div>';}
 function tabla(arr,conDescripcion=false){let h='<div class="oic-scroll table-responsive"><table class="table table-sm table-striped oic-table"><thead><tr><th>Referencia</th><th>Tipo</th><th>Regla</th>'+(conDescripcion?'<th style="min-width:360px">Descripción Oracle</th>':'')+'<th class="text-end">Débito</th><th class="text-end">Crédito</th><th class="text-end">Oracle neto</th><th class="text-end">Visor</th><th class="text-end">Diferencia</th><th>Estado</th></tr></thead><tbody>';if(!arr.length)h+='<tr><td colspan="'+(conDescripcion?10:9)+'" class="text-center text-muted py-4">Sin movimientos</td></tr>';arr.forEach(x=>h+='<tr><td><b>'+esc(x.referencia)+'</b></td><td>'+esc(x.tipo)+'</td><td>'+esc(x.regla)+'</td>'+(conDescripcion?'<td style="min-width:360px;white-space:normal">'+esc(x.descripcion||'')+'</td>':'')+'<td class="text-end">$'+money(x.debito)+'</td><td class="text-end">$'+money(x.credito)+'</td><td class="text-end">$'+money(x.oracle)+'</td><td class="text-end">$'+money(x.visor)+'</td><td class="text-end '+(Math.abs(Number(x.diferencia))>.05?'text-danger fw-bold':'')+'">$'+money(x.diferencia)+'</td><td>'+esc(x.estado)+'</td></tr>');return h+'</tbody></table></div>';}
 function expTabla(arr){let h='<div class="mb-2 small text-muted">Listado de EXP / Caja chica. Pique en cualquier EXP para ver u ocultar sus CFDI de detalle.</div><div class="oic-exp-list">';if(!arr.length)return '<div class="text-center text-muted py-4">Sin EXP</div>';arr.forEach((x,i)=>{const id='oicExpDet'+i;const ok=x.estado==='CONCILIADO';h+='<div class="oic-exp-item"><button type="button" class="oic-exp-head" data-bs-toggle="collapse" data-bs-target="#'+id+'" aria-expanded="false" aria-controls="'+id+'"><div class="oic-exp-left"><i class="bi bi-chevron-right oic-exp-arrow"></i><span class="oic-exp-ref">'+esc(x.referencia)+'</span><span class="badge '+(ok?'bg-success':'bg-danger')+'">'+esc(x.estado)+'</span><span class="badge bg-light text-dark border">'+(x.detalles||[]).length+' CFDI</span></div><div class="oic-exp-totals">Oracle <b>$'+money(x.oracle)+'</b> · Visor <b>$'+money(x.visor)+'</b> · Dif. <b class="'+(Math.abs(Number(x.diferencia))>.05?'text-danger':'text-success')+'">$'+money(x.diferencia)+'</b></div></button><div id="'+id+'" class="collapse oic-exp-body"><div class="oic-scroll table-responsive"><table class="table table-sm table-striped mb-0 oic-table"><thead><tr><th>UUID</th><th>Proveedor</th><th>Factura</th><th>Ref. pago</th><th class="text-end">IVA</th></tr></thead><tbody>';if(!(x.detalles||[]).length)h+='<tr><td colspan="5" class="text-center text-muted py-3">Sin detalle CFDI relacionado</td></tr>';else (x.detalles||[]).forEach(d=>h+='<tr><td>'+esc(d.uuid)+'</td><td>'+esc(d.nombre)+'</td><td>'+esc((d.serie||'')+' '+(d.folio||''))+'</td><td>'+esc(d.ref_pago)+'</td><td class="text-end">$'+money(d.iva)+'</td></tr>');h+='</tbody></table></div></div></div>';});return h+'</div>';}
 function transTabla(arr){
  const total=arr.reduce((a,x)=>a+Number(x.iva||0),0);
  const aplicados=arr.filter(x=>!!x.oracle_aplico);
  const noAplicados=arr.filter(x=>!x.oracle_aplico);
  const totalAplicado=aplicados.reduce((a,x)=>a+Number(x.iva||0),0);
  const totalNoAplicado=noAplicados.reduce((a,x)=>a+Number(x.iva||0),0);
  let h='<div class="row g-2 mb-2">'
    +'<div class="col-6 col-md-3"><div class="oic-kpi py-2"><div class="small text-muted">Registros</div><b>'+arr.length+'</b></div></div>'
    +'<div class="col-6 col-md-3"><div class="oic-kpi py-2"><div class="small text-muted">IVA tránsito</div><b>$'+money(total)+'</b></div></div>'
    +'<div class="col-6 col-md-3"><div class="oic-kpi py-2"><div class="small text-muted">Aplicó Oracle ('+aplicados.length+')</div><b class="text-success">$'+money(totalAplicado)+'</b></div></div>'
    +'<div class="col-6 col-md-3"><div class="oic-kpi py-2"><div class="small text-muted">No aplicó Oracle ('+noAplicados.length+')</div><b class="text-warning">$'+money(totalNoAplicado)+'</b></div></div>'
    +'</div>';
  h+='<div class="oic-scroll table-responsive"><table class="table table-sm table-striped oic-table"><thead><tr><th>Grupo</th><th>UUID</th><th>Proveedor</th><th class="text-end">IVA</th><th>Esperado</th><th>Aplicó Oracle</th><th>Estado</th></tr></thead><tbody>';
  if(!arr.length)h+='<tr><td colspan="7" class="text-center text-muted">Sin tránsito</td></tr>';
  arr.forEach(x=>h+='<tr><td>'+esc(x.grupo)+'</td><td>'+esc(x.uuid)+'</td><td>'+esc(x.proveedor)+'</td><td class="text-end">$'+money(x.iva)+'</td><td>'+esc(x.esperado)+'</td><td>'+(x.oracle_aplico?'SÍ':'NO')+'</td><td><span class="badge '+(x.estado==='OK'?'bg-success':'bg-warning text-dark')+'">'+esc(x.estado)+'</span></td></tr>');
  if(arr.length)h+='<tr class="table-light fw-bold"><td colspan="3" class="text-end">TOTAL</td><td class="text-end">$'+money(total)+'</td><td></td><td colspan="2">Aplicó: $'+money(totalAplicado)+' · No aplicó: $'+money(totalNoAplicado)+'</td></tr>';
  return h+'</tbody></table></div>';
 }
 function visorTabla(arr){let h='<div class="oic-scroll table-responsive"><table class="table table-sm table-striped oic-table"><thead><tr><th>UUID</th><th>RFC</th><th>Proveedor</th><th>Factura</th><th>Fecha fiscal</th><th>Ref pago</th><th class="text-end">IVA</th></tr></thead><tbody>';if(!arr.length)h+='<tr><td colspan="7" class="text-center text-muted">Sin movimientos</td></tr>';arr.forEach(x=>h+='<tr><td>'+esc(x.uuid)+'</td><td>'+esc(x.rfc)+'</td><td>'+esc(x.nombre)+'</td><td>'+esc((x.serie||'')+' '+(x.folio||''))+'</td><td>'+esc(x.fecha_fiscal)+'</td><td>'+esc(x.ref_pago)+'</td><td class="text-end">$'+money(x.iva)+'</td></tr>');return h+'</tbody></table></div>';}
 function render(r){lastId=r.id_conciliacion||0;const s=r.resumen||{};const k=[['Débito Oracle',s.oracle_debito],['Crédito Oracle',s.oracle_credito],['Neto Oracle',s.oracle_neto],['IVA Visor',s.visor_iva],['Diferencia',s.diferencia_global],['Conciliados',s.conciliados]];$('#oicKpis').html(k.map(x=>'<div class="col-6 col-md-2"><div class="oic-kpi"><div class="small text-muted">'+x[0]+'</div><b>'+((typeof x[1])==='number'&&x[0]!=='Conciliados'?'$'+money(x[1]):esc(x[1]))+'</b></div></div>').join(''));$('#oicImp').html(importTabla(r.importados_oracle||[]));$('#oicConc').html(tabla(r.conciliados||[]));$('#oicDif').html(tabla(r.diferencias||[],true));$('#oicOra').html(tabla(r.oracle_sin_conciliar||[]));$('#oicVis').html(visorTabla(r.visor_sin_conciliar||[]));$('#oicExp').html(expTabla(r.exp||[]));const tr=(r.transito||[]);const trAnt=tr.filter(x=>String(x.grupo||'').toUpperCase().indexOf('MES ANTERIOR')===0);const trSig=tr.filter(x=>String(x.grupo||'').toUpperCase().indexOf('TRÁNSITO A MES POSTERIOR')===0||String(x.grupo||'').toUpperCase().indexOf('TRANSITO A MES POSTERIOR')===0);$('#oicTraAnt').html(transTabla(trAnt));$('#oicTraSig').html(transTabla(trSig));$('#oicResultados').show();$('#oicExport').prop('disabled',!lastId);}
 $('#oicBtnSubir').on('click',function(){const f=$('#oicArchivo')[0].files[0];if(!f)return Swal.fire('Archivo','Seleccione el Excel Oracle .xlsx','warning');const fd=new FormData();fd.append('anio',$A.val());fd.append('mes',$M.val());fd.append('archivo',f);$E.text('Subiendo y detectando encabezados...');$.ajax({url:'ajax/oracle_iva_subir.php',method:'POST',data:fd,processData:false,contentType:false,dataType:'json'}).done(r=>{if(!r.ok)throw new Error(r.error||'Error');$E.html('<span class="text-success">Archivo importado: '+r.filas+' movimientos, '+r.encabezados+' encabezado(s) detectado(s).</span>');archivos();setTimeout(()=>$S.val(r.id_archivo),250);}).fail(x=>Swal.fire('Error',x.responseJSON?.error||'No se pudo subir el archivo','error'));});
 $('#oicBtnConciliar').on('click',function(){if(!$S.val())return Swal.fire('Archivo','Seleccione un archivo cargado','warning');Swal.fire({title:'Conciliando mes completo...',allowOutsideClick:false,didOpen:()=>Swal.showLoading()});$.post('ajax/oracle_iva_conciliar.php',{anio:$A.val(),mes:$M.val(),id_archivo:$S.val()},null,'json').done(r=>{Swal.close();if(!r.ok)return Swal.fire('Error',r.error,'error');render(r.resultado);$E.html('<span class="text-success">Conciliación terminada. Se cruzó Oracle contra detalle DIOT, EXP y tránsito.</span>');}).fail(x=>{Swal.close();Swal.fire('Error',x.responseJSON?.error||'No se pudo conciliar','error');});});
 $('#oicExport').on('click',()=>{if(lastId)window.location='ajax/oracle_iva_exportar.php?id_conciliacion='+lastId;});$('#oicRecargar').on('click',archivos);$A.add($M).on('change',archivos);archivos();})();
</script>
