-- Conciliación IVA Oracle ↔ Visor. Las tablas también se crean automáticamente al abrir/usar el módulo.
CREATE TABLE IF NOT EXISTS oracle_iva_archivos (
 id_archivo BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,id_empresa INT NOT NULL,anio SMALLINT UNSIGNED NOT NULL,mes TINYINT UNSIGNED NOT NULL,nombre_original VARCHAR(255) NOT NULL,ruta_archivo VARCHAR(1200) NOT NULL,sha256 CHAR(64) NOT NULL,hoja_principal VARCHAR(190),filas_importadas INT NOT NULL DEFAULT 0,encabezados_detectados INT NOT NULL DEFAULT 0,id_usuario INT,fecha_subida DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id_archivo),KEY idx_oia_empresa_periodo(id_empresa,anio,mes,fecha_subida),CONSTRAINT fk_oia_empresa FOREIGN KEY(id_empresa) REFERENCES empresas(id_empresa) ON DELETE CASCADE,CONSTRAINT fk_oia_usuario FOREIGN KEY(id_usuario) REFERENCES usuarios(id_usuario) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS oracle_iva_movimientos (
 id_movimiento BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,id_archivo BIGINT UNSIGNED NOT NULL,id_empresa INT NOT NULL,hoja VARCHAR(190) NOT NULL,renglon_excel INT NOT NULL,cuenta VARCHAR(100),cuenta_descripcion VARCHAR(700),cuenta_tipo VARCHAR(20) NOT NULL DEFAULT 'OTRO',origen VARCHAR(120),categoria VARCHAR(120),fecha_contable DATE,clase_evento VARCHAR(120),numero_transaccion VARCHAR(190),descripcion TEXT,debito DECIMAL(20,6) NOT NULL DEFAULT 0,credito DECIMAL(20,6) NOT NULL DEFAULT 0,referencia_factura VARCHAR(190),tipo_referencia VARCHAR(20) NOT NULL DEFAULT 'OTRO',PRIMARY KEY(id_movimiento),KEY idx_oim_archivo(id_archivo,renglon_excel),KEY idx_oim_empresa_ref(id_empresa,referencia_factura),KEY idx_oim_archivo_tipo(id_archivo,cuenta_tipo),CONSTRAINT fk_oim_archivo FOREIGN KEY(id_archivo) REFERENCES oracle_iva_archivos(id_archivo) ON DELETE CASCADE,CONSTRAINT fk_oim_empresa FOREIGN KEY(id_empresa) REFERENCES empresas(id_empresa) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS oracle_iva_conciliaciones (
 id_conciliacion BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,id_archivo BIGINT UNSIGNED NOT NULL,id_empresa INT NOT NULL,anio SMALLINT UNSIGNED NOT NULL,mes TINYINT UNSIGNED NOT NULL,tolerancia DECIMAL(10,4) NOT NULL DEFAULT .05,resultado_json LONGTEXT NOT NULL,id_usuario INT,fecha_conciliacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id_conciliacion),KEY idx_oic_empresa_periodo(id_empresa,anio,mes,fecha_conciliacion),KEY idx_oic_archivo(id_archivo),CONSTRAINT fk_oic_archivo FOREIGN KEY(id_archivo) REFERENCES oracle_iva_archivos(id_archivo) ON DELETE CASCADE,CONSTRAINT fk_oic_empresa FOREIGN KEY(id_empresa) REFERENCES empresas(id_empresa) ON DELETE CASCADE,CONSTRAINT fk_oic_usuario FOREIGN KEY(id_usuario) REFERENCES usuarios(id_usuario) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
